[dev]
    targetPort = 4000
    port = 8080

# Production redirects to route API calls to Netlify functions
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/api/:splat"
    status = 200


# Build configuration
[build]
    command = "bun run build"
    publish = "dist"

[build.environment]
    NODE_VERSION = "18"
